language: python
#python:
#  - "3.8"

cache:
  pip: true
install:
  - pip install -r requirements.txt
  - pip install mkdocs mkdocs-material pymdown-extensions pygments # Install the required dependencies

addons:
  sonarcloud:
    organization: "jliekenbrock"
    token: $SONAR_TOKEN

jobs:
  include:
    - stage: unit tests
      script:
        - pytest
    - stage: metrics
      script:
        - sonar-scanner
    - stage: generate documentation
      script:
        - mkdocs build --verbose --clean --strict
        - pdoc --force --html --output-dir docs components
    - stage: deploy
      script: rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
      deploy:
        provider: heroku
        api_key: $HEROKU_TOKEN
          app: 
            main: lyricsvis
    - stage: deploy
      script: pass
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
        local_dir: site
        on:
          branch: main

