language: python
#python:
#  - "3.8"

cache:
  pip: true
install:
  - pip install -r requirements.txt

addons:
  sonarcloud:
    organization: "jliekenbrock"
    token: $SONAR_TOKEN

# other script steps might be done before running the actual analysis
# command to run tests
script:
  - pytest
  # It is also possible to run sonar-scanner like this instead of integrating it directly in github
  #- sonar-scanner
  - pdoc --force --html --output-dir docs components

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: main
  local_dir: docs/components

before_deploy:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0

deploy:
  provider: heroku
  api_key: $HEROKU_TOKEN
  app: 
    main: lyricsvis