language: python
#python:
#  - "3.8"

cache:
  pip: true
install:
  - pip install -r requirements.txt
  - pip install mkdocs mkdocs-material pymdown-extensions pygments 

addons:
  sonarcloud:
    organization: "jliekenbrock"
    token: $SONAR_TOKEN

script:
  - pytest
  - sonar-scanner

#deploy:
#  provider: pages
#  skip_cleanup: true
#  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
#  keep_history: true
#  on:
#    branch: main
#  local_dir: docs/components


before_deploy:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
  - mkdocs build --verbose --clean --strict # Build a local version of the docs
  #- pdoc --force --html --output-dir site components

deploy: # Deploy documentation to Github in the gh_pages branch
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  #keep_history: true
  target_branch: gh-pages
  local_dir: site
  on:
    branch: main
  provider: heroku
  api_key: $HEROKU_TOKEN
  app: 
    main: lyricsvis