language: python
python:
  - "3.8"

cache:
  pip: true
install:
  - pip install -r requirements.txt
  - pip install mkdocs mkdocs-material pymdown-extensions pygments # Install the required dependencies

addons:
  sonarcloud:
    organization: "jliekenbrock"
    token: $SONAR_TOKEN

# other script steps might be done before running the actual analysis
# command to run tests
script:
  - pytest
  # It is also possible to run sonar-scanner like this instead of integrating it directly in github
  - sonar-scanner

before_deploy:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
  - mkdocs build --verbose --clean --strict # Build a local version of the docs
  - pdoc --force --html --output-dir docs components

deploy:
  - provider: heroku
    api_key: $HEROKU_TOKEN
    app: 
      main: lyricsvis
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    local_dir: site
    on:
      branch: main