site_name: Project Documentation

plugins:
  - search
  - build_plantuml:
      render: "server" # or "local" for local rendering
      bin_path: "/usr/local/bin/plantuml" # ignored when render: server
      server: "http://www.plantuml.com/plantuml" # offical plantuml server
      output_format: "svg" # or "png"
      diagram_root: "docs/UML" # should reside under docs_dir
      output_folder: ""
      input_folder: ""
      input_extensions: "" # comma separated list of extensions to parse, by default every file is parsed